---
- name: configure MariaDB on CentOS
  include_tasks: centos_configure_mariadb.yaml
  when:
    - ansible_os_family == "RedHat"

- name: configure MariaDB on Debian
  include_tasks: debian_configure_mariadb.yaml
  when:
    - ansible_os_family == "Debian"