--- 
- name: Update all packages 
  apt: 
    name: "*"
    state: latest 
    update_cache: yes
    force_apt_get: yes

- name: Install packeges for MariaDB
  apt: 
    name: "{{ packages_debian }}"
    state: latest

- name: Started and Enabled MariaDB
  service:
    name: mariadb 
    enabled: yes
    state: started 

- name: Configurations root password for MariaDB
  command: mysqladmin -u root password {{ mysql_root_pass }}